print("Here,We have few quotes/wishes for you")
print("\n")
print("for 'Morning wishes/quotes' press 'M' \nfor 'Afternon  wishes/quotes' press'A' \nfor 'Evening  wishes/quotes' press 'E' \nfor 'Night  wishes/quotes'press'N'")
print("\n")
action = input("Enter here!: ")
print("\n")
if action == "M":
    print("Every day is new opportunity for us, Have a Great day!")
    print("\n")
    print("People save good memories in PENDRIVE & bad memories in mind just change loscation life will automatically changes,\n Have a joyful day!")
    print("\n")
    print("blessing of grace and peace be with you today & everyday")
    print("\n")
    print("Keep spearding positivity everyday wherever you go")
    print("\n")
    print("Feed your mind with positive thoughts ans atract great thing in yuor life")
    print("\n") 
    print("Hope your morning is as your smile")
    print("\n")  
    print("Smile & be be happy ,be grateful for good things in your life")
elif action == "A":
    print("Night has gone, morning has gone but I have noon to say you, Good Afternoon")
    print("\n")
    print("Life is 10% WHAT HAPPENS TO YOU!& 90% HOW YOU REACT IT")
    print("\n")
    print("You're safe not because of absence of danger but because presence of god")
    print("\n")
    print("Good,Better,Bestnever let it rest till,GOOD is BETTER, BETTER is BEST")
    print("\n")
    print("Lose yourself in nature and fine piece")
elif action == "E":
    print("Happiness can't be far behind a greteful heart & a peaceful mind")
    print("\n")
    print("I wish this evening make you feel the beauty of day")
    print("\n")
    print("LIFE IS SHORT\n Spend it with the who make you feel happy")
    print("\n")
    print("Evening is the time for peace where there is no tension")
    print("\n")
    print("Always be there for people who matter the most to you")
elif action == "N":
    print("May your dreams be filled with cutest that \nyou've always longed for lovely night and beautiful dreams")
    print("\n")
    print("wishing you peaceful night's rest")
    print("\n")
    print("Stars can't shine without darkness")
    print("\n")
    print("if you can't do great thing ,do small things in great way")
    print("\n")
    print("I hope you have dreams as sweet as Iam")
